[tool.mypy]
python_version = "3.12"
show_error_codes = true
no_implicit_optional = true
warn_return_any = true
warn_unused_ignores = true
warn_unused_configs = true
ignore_missing_imports = true
exclude = ["venv"]
