# .github/workflows/demo.yml

name: workflow-2

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["workflow-1"]
    types: [completed]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  if: ${{ github.event.workflow_run.conclusion == 'success'}}
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo workflow2
